- name: restart kube-apiserver
  systemd: 
    state: restarted
    daemon_reload: yes
    name: kube-apiserver 

- name: restart kube-controller-manager
  systemd: 
    state: restarted
    daemon_reload: yes
    name: kube-controller-manager 

- name: restart kube-scheduler
  systemd: 
    state: restarted
    daemon_reload: yes
    name: kube-scheduler 

    