- name: get checksums file
  local_action:
    module: get_url
    url: "{{ etcd_download_url }}/{{ etcd_version }}/SHA256SUMS"
    dest: /tmp/etcd-{{ etcd_version }}-sha256sums
  become: False

- debug:
    var:
      '{{ lookup("file", "/tmp/etcd-"+etcd_version+"-sha256sums").splitlines() }}'
      
- name: "Download etcd {{ etcd_version }}"
  get_url:
    url: "{{ etcd_download_url }}/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    dest: "/tmp/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    checksum: 'sha256:{{ etcd_checksums[0].split()[0] }}'
  vars:
    etcd_checksums: '{{ lookup("file", "/tmp/etcd-"+etcd_version+"-sha256sums").splitlines() | select("match", ".*etcd-"+ etcd_version +"-linux-amd64.tar.gz$") | list }}'



