- hosts: all
  gather_facts: False
  vars:
    ansible_become: False
  tasks:
  - name: Wait for port 22 to become open on the host
    local_action:
      module: wait_for
      port: 22

  - name: Usun klucz z known_hosts
    delegate_to: localhost
    known_hosts:
      name: "{{ ansible_host }}"
      state: absent

  - name: Dodaj klucz do known_hosts
    local_action:
      module: known_hosts
      name: "{{ ansible_host }}"
      key: "{{ lookup('pipe', 'ssh-keyscan -tecdsa -p 22 ' + ansible_host  | quote ) }}"
      state: present
      hash_host: yes

