- name: create downloads dir
  file: 
    state: directory
    path: "{{ ansible_env.HOME }}/downloads"

# Optionally we could create a temporary directory
- name: create local tmp directory for checksums
  local_action:
    module: file
    state: directory
    path: /tmp/k8s-checksums-{{ kubernetes_version }}-{{ k8s_architecture }}
  become: False 

- name: download sha256 checksums
  local_action:
    module: get_url
    url: "{{ k8s_download_url }}/{{ kubernetes_version }}/bin/{{ k8s_architecture }}/{{ item }}.sha256"
    dest: /tmp/k8s-checksums-{{ kubernetes_version }}-{{ k8s_architecture }}
  become: False  
  loop:
  - kubectl
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  
- name: "download kubernetes binaries - version: {{ kubernetes_version }}"
  get_url: 
    url: "{{ k8s_download_url }}/{{ kubernetes_version }}/bin/{{ k8s_architecture }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: a+x
    checksum: "sha256:{{ checksum_var }}"
  vars:
    checksum_var: "{{ lookup('file', '/tmp/k8s-checksums-'+kubernetes_version+'-'+k8s_architecture+'/'+item+'.sha256') }}"
  loop:
  - kubectl
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler

- name: template service config - kube-apiserver
  template: 
    src: "kube-apiserver.j2.service"
    dest: "/etc/systemd/system/kube-apiserver.service"
  notify:
  - "restart kube-apiserver"

- name: template service config
  template: 
    src: "kube-controller-manager.j2.service"
    dest: "/etc/systemd/system/kube-controller-manager.service"
  notify:
  - "restart kube-controller-manager"

- name: template service config
  template: 
    src: "kube-scheduler.j2.service"
    dest: "/etc/systemd/system/kube-scheduler.service" 
  notify:
  - "restart kube-scheduler"
  
- name: template kube-scheduler yaml config
  template: 
    src: kube-scheduler.j2.yaml
    dest: "{{ kubernetes_configs_dir }}/kube-scheduler.yaml"
  notify:
  - "restart kube-scheduler"

- name: start kube-apiserver
  systemd: 
    state: started
    daemon_reload: yes
    name: kube-apiserver 
    enabled: True

- name: start kube-controller-manager
  systemd: 
    state: started
    daemon_reload: yes
    name: kube-controller-manager 
    enabled: True

- name: start kube-scheduler
  systemd: 
    state: started
    daemon_reload: yes
    name: kube-scheduler 
    enabled: True

# TODO check all controlplane component healthschecks. kubectl get componentstatuses is deprecated since 1.19.
# test healthchecks

- name: Wait for kube-apiserver port to become open
  wait_for:
    port: 6443
    delay: 10
    timeout: 300

- name: get kube-apiserver healthcheck endpoint
  uri:
    url: "https://{{ private_ip_address }}:6443/livez"
    return_content: yes
    validate_certs: no
  register: kube_apiserver_healthcheck_result

- name: test kube-apiserver healthcheck response
  fail:
    msg: 'kube-apiserver healthcheck failed'
  when: "'ok' not in kube_apiserver_healthcheck_result.content"

- name: Wait for kube-controller-manager port to become open
  wait_for:
    port: 10252
    delay: 10
    timeout: 300

- name: get kube-controller-manager healthcheck endpoint
  uri:
    url: "http://{{ private_ip_address }}:10252/healthz"
    return_content: yes
    validate_certs: no
  register: kube_controller_manager_healthcheck_result

- name: test kube-controller-manager healthcheck response
  fail:
    msg: 'kube-controller-manager healthcheck failed'
  when: "'ok' not in kube_controller_manager_healthcheck_result.content"

- name: Wait for kube-scheduler port to become open
  wait_for:
    port: 10251
    delay: 10
    timeout: 300

- name: get kube-scheduler healthcheck endpoint
  uri:
    url: "http://{{ private_ip_address }}:10251/healthz"
    return_content: yes
    validate_certs: no
  register: kube_scheduler_healthcheck_result

- name: test kube-scheduler healthcheck response
  fail:
    msg: 'kube-scheduler healthcheck failed'
  when: "'ok' not in kube_scheduler_healthcheck_result.content"

